default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: localhost

development:
  <<: *default
  database: geeker_development

test:
  <<: *default
  database: geeker_test

production:
  <<: *default
  database: geeker_production